# Configuration for Label Actions (v5 format)
# Auto-labels PRs based on changed files

feature:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*.ts'
          - '!src/**/*.test.ts'
          - '!src/**/*.spec.ts'

bug:
  - changed-files:
      - any-glob-to-any-file:
          - 'fix/**/*'
          - 'bugfix/**/*'
          - 'hotfix/**/*'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**/*'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'

ci-cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/actions/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**/*'
          - 'src/**/*.test.ts'
          - 'src/**/*.spec.ts'
          - 'jest.config.js'

ui:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/ui/**/*'
          - 'styles/**/*'
          - '*.css'

api:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/api/**/*'

auth:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/auth/**/*'

services:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/services/**/*'

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'SECURITY.md'
          - '.github/dependabot.yml'
          - 'src/auth/**/*'

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - '*.json'
          - '*.yml'
          - '*.yaml'
          - '.eslintrc*'
          - '.prettierrc*'
          - 'tsconfig.json'
